#define CCC(val)  do {fprintf(stderr, "%4d %16s %16s %16s: %c\n", __LINE__, __FILE__,  __func__, #val, val); fflush(stderr);} while (0)
#define DDD(val)  do {fprintf(stderr, "%4d %16s %16s %16s: %d\n", __LINE__, __FILE__,  __func__, #val, val); fflush(stderr);} while (0)
#define PPP(val)  do {fprintf(stderr, "%4d %16s %16s %16s: %p\n", __LINE__, __FILE__,  __func__, #val, val); fflush(stderr);} while (0)
#define LLL(val)  do {fprintf(stderr, "%4d %16s %16s %16s: %ld\n", __LINE__, __FILE__,  __func__, #val, val); fflush(stderr);} while (0)
#define SSS(val)  do {fprintf(stderr, "%4d %16s %16s %16s: %s\n", __LINE__, __FILE__,  __func__, #val, val); fflush(stderr);} while (0)
#define FFF(val)  do {fprintf(stderr, "%4d %16s %16s %16s: %f\n", __LINE__, __FILE__,  __func__, #val, val); fflush(stderr);} while (0)
#define NNN       do {fprintf(stderr, "%4d %16s %16s\n", __LINE__, __FILE__,  __func__); fflush(stderr);} while (0)
#define ERR     do {NNN; puts("Good Bye"); exit(1);} while (0)
#define RERR(fd) do {perror("Recv Error"); NNN; close(fd); pthread_exit(NULL);} while (0)
#define ERR2    do {perror("ERROR"); NNN; pthread_exit(NULL);} while (0)
